### ISSUE TITLE
Broaden support for stable hlo dot general

### ISSUE THREAD

**Issue by AleksKnezevic** [tenstorrent/tt-mlir#1047]
Currently, stable hlo dot general only works without any transposes on inputs. Broaden the conversion so that it supports transpose. Add tests in tt-torch and tt-mlir

**Comment by LPanosTT** [comment]
My plan is to create a `ttir.dot_general` op that mirrors `stablehlo.dot_general`. The `stablehlo.dot_general` op has a number of extra attributes to describe in detail how to break down the operation into a series of multiply-accumulates. That is, which batch dimension to loop over, what precision for compute and accumulate, etc. We will assert that the dot algorithm attribute of the `stablehlo.dot_general` is `None` during conversion as we only want to match the cases where this op can be represented as a simple sequence of matmuls. 

As of right now it seems to me that the only attribute from `stablehlo.dot_general` that we need to keep in `ttir.dot_general` are the LHS/RHS contracting dimensions as those define what matmul(s) need to happen to get the result. I will come up with some algorithm to deduce the order of transposes/matmuls necessary to produce the same outcome in `TTIRToTTIRDecompositionPass`

**Comment by LPanosTT** [comment]
Perhaps scratch that first idea.

I just checked what a stablehlo graph of a more outlandish einsum looks like and torch-mlir ended up doing all the transpose stuff for us, the stablehlo.dot_general in there is already a simple matmul. From the tt-torch side it looks like we can always expect `stablehlo.dot_general` to correspond to a single matmul without any fluff.


In tt-xla the exact same einsum fails at VHLO --> SHLO conversion. It looks like the vhlo.dot_general_v1  op doesn't get pattern matched during conversion for whatever reason and so it's leftover in the graph. Since that dialect is marked illegal after conversion it fails there.

Because of what happens on the xla side I'm not 100% sure how we want to handle it. For now, I guess we can match only the `stablehlo.dot_general` ops that correspond to a clean matmul, which should be satisfactory for the tt-torch path. As for the tt-xla path, if in the future that conversion from VHLO to SHLO is supported, and we find that the xla takes advantage of the complex scope of `stablehlo.dot_general`, we can always make a `ttir.dot_general` then since we will not be very entrenched in the current conversion logic - that being only matching `stablehlo.dot_general` ops which are just matmuls.

@AleksKnezevic @uazizTT @mmanzoorTT what do you think?

**Comment by uazizTT** [comment]
@LPanosTT This is the [spreadsheet](https://docs.google.com/spreadsheets/d/1QDDa5WyoVx5lv_yS8qAyJPf9a3h15TO1/edit?pli=1&gid=932429241#gid=932429241) with the issues related to stablehlo.dot_general, it may not be possible to go through each of them yet, but still gives you an idea.

**Comment by LPanosTT** [comment]
Fix here: https://github.com/tenstorrent/tt-mlir/pull/1311

**Comment by mrakitaTT** [comment]
> I don't think we should be implementing a complex dot general op in ttir unless we see a need for it from models. For the time being (since we're only matching simple matmul) we can keep as is (i.e. converting shlo.dot_general to ttir.matmul). Once more models come up in jax, if we see the need for it, we can add a ttir.dot_general with more complex behaviour.

@AleksKnezevic I agree.

Btw thanks for tagging me here, this conversation shed some light on possible causes for issue https://github.com/tenstorrent/tt-xla/issues/41 that we wanted to investigate :) We might need to legalize `vhlo.dot_general_v1` and then treat it same as `shlo.dot_general`, or even better contribute to stablehlo project with a fix, we'll investigate more.

**Comment by mmanzoorTT** [comment]
IIRC, @ddilbazTT was having some issues with `vhlo.dot_general_v1` when she was trying to write some tt-xla tests for `gather` op. She got it fixed by uplifting stablehlo and llvm-project repos. She can add more details about her investigation.

**Comment by ddilbazTT** [comment]
> IIRC, [@ddilbazTT](https://github.com/ddilbazTT) was having some issues with `vhlo.dot_general_v1` when she was trying to write some tt-xla tests for `gather` op. She got it fixed by uplifting stablehlo and llvm-project repos. She can add more details about her investigation.

I was having the following error:
`error: failed to legalize operation 'vhlo.gather_v1' that was explicitly marked illegal` which went away with stablehlo and llvm uplifts, as Asif mentioned. But I did not run into dot_general errors.

**Comment by LPanosTT** [comment]
Fixes have been merged
