### ISSUE TITLE
Embedding input in TILE layout, despite ttnn.embedding doesn't support it

### ISSUE THREAD

**Issue by dgolubovicTT** [tenstorrent/tt-mlir#1215]
When running Llama prefil I ran into following assert on metal:

![Image](https://github.com/user-attachments/assets/11e3501b-dc9b-4a9a-9b5b-a96d1b4faa1b)

It says that input to the embedding op is in tile layout. When I check ttnn IR that is generated, I see that input %3 is derived from %1 (applied ttnn.to_device and type_cast) which is in tile layout.

This is how ttir looks like:

![Image](https://github.com/user-attachments/assets/dc74dbb4-5b34-44ba-a32f-a1b394a0b70a)

And here is ttnn IR part relevant to this embedding op. (Note that this is not the whole ttnn IR but just part that refers to embedding).
[Llama_embedding_input_mem_layout.json](https://github.com/user-attachments/files/17681981/Llama_embedding_input_mem_layout.json)

**Comment by dgolubovicTT** [comment]
Here is the ttir and ttn of embedding test that fails with same error. Use this for repro...[Embedding_input_tile_layout_ttnn.txt](https://github.com/user-attachments/files/17714626/Embedding_input_tile_layout_ttnn.txt)
[Embedding_input_tile_layout_ttir.txt](https://github.com/user-attachments/files/17714632/Embedding_input_tile_layout_ttir.txt)

**Comment by mtopalovicTT** [comment]
Problem is following. If we have below IR:
`ttir.to_layout()`
`ttir.typecast()`
`ttir.embedding()`

To layout op conversion to ttnn checks if users of to_layout are operations which require row_major layout. If there is such user we force to_layout op conversion into row_major.

1. Since typecast is not among those ops (nor it should be) we force to_layout into tile layout.
This will result in error when running program since after to_layout op, input tensor for typecast will be in tile layout and after typecast (which just cast tensor from one data type to other) tensor layout will remain unchanged and we will run into assert into embedding requesting that first tensor input should be in row major when embedding on device.
2. When doing typecast we don't have any verifier which confirms that both input tensor and output tensor layout attributes differ only in DataType. In the case above we end up with input which is tile layout and output which is scalar. So we can end up like this:
`ttnn.typecast(%2) { dtype = tt.data_type<Uint32> } (tensor<64x64xi32, tt.layout<...memref<2x2x!tt.tile<32x32xi32> ... >) -> tensor<64x64xi32, tt.layout<...memref<64x64xi32 ...> ... >`
3. If we for example typecast from i32 to uin32 we only change typecast op attribute to reflect this change, we don't change RankedTensorType. So typecast will look like
`ttnn.typecast(%2) { dtype = tt.data_type<UInt32> } (tensor<2x2xi32>) -> tensor<2x2xi32>`
4. For the example shown in this issue typecast is actually redundant operation since we  typecast to same type.
`%1 = "ttir.typecast"(%arg0, %0) <{operandSegmentSizes = array<i32: 1, 1>, operand_constraints = [#any_device, #any_device]}> {dtype = "Int32"} : (tensor<1x12xi32>, tensor<1x12xi32>) -> tensor<1x12xi32>`

**Comment by dgolubovicTT** [comment]
If I understand correctly second point: typecast op doesn't change memory layout from tile to row major, but from ttnn.typecast we see that layout is changed on output? 
Also looking into ttnn IR it seems like to_device changes data type from int32 to uint32. And then we have type cast after that...

**Comment by dgolubovicTT** [comment]
@mtopalovicTT As we agreed offline I found where we add this cast in forge, and removed it (turns out we were casting no matter the input df).
Now running llama embedding test with blofat16 produces tensor mismatch on output. Using float32 wights asserts in metal, therefore the need for 'blofat16'. I am attaching simple ttir repro. [Llama_emb_bfloat16_tensor_mismatch_ttir.txt](https://github.com/user-attachments/files/17748506/Llama_emb_bfloat16_tensor_mismatch_ttir.txt)
