### ISSUE TITLE
Handle max_pool2d input dataformat float32

### ISSUE THREAD

**Issue by dgolubovicTT** [tenstorrent/tt-mlir#1389]
When I run resnet test from forge I get unexpeted error: 

`loc("max_pool2d_17"("forward":4294967295:3591)): error: 'ttnn.max_pool2d' op ttnn.max_pool2d currently only supports an input type of bfloat16. Recieved 'f32'.`

Turns out it is due to assert in verify ` mlir::tt::ttnn::Conv2dOp::verify()` added in [PR](https://github.com/tenstorrent/tt-mlir/commit/5fd26305487fd4b28eabd3f5de826f35d65b09d0#diff-a6cb8b5b9ca05403b2ffed57b2fc9e353ac983c5f7ae34c7a1cb385e7af2777fR93).

So If ttnn.max_pool2d only supports bfloat16 we shouldn't just fail compile if its input is float32. We should probably add a cast op to handle this and move on with compile. 
 
@sdjordjevicTT can we prioritize this because it is a blocker for ResNet bringup?
fyi @nvukobratTT

**Comment by sdjordjevicTT** [comment]
@dgolubovicTT I agree with you, you shouldn't worry about the data format constraints from Forge-FE.

Some TTNN ops can automatically do the cast, but some ops fail if the inputs aren't in the specified data format. We have defined the issue on our side to handle such cases:
https://github.com/tenstorrent/tt-mlir/issues/1433

For each workaround that we introduce in the tt-mlir stack, we are filing an issue on the metal side to track the resolution. Once the issue is resolved on the metal side, we will remove the workarounds from the compiler code.

**Comment by dgolubovicTT** [comment]
This sounds promising. Thanks!
