### ISSUE TITLE
Explorer - CI is timing out and hanging

### ISSUE THREAD

**Issue by vprajapati-tt** [tenstorrent/tt-mlir#1511]
- Unsure of why exactly this is happening. When running locally, I noticed that it would open a webpage and restart the server for every testcase. This may potentially be the cause (it's also just inefficient)
- Need to do more investigation into the fixture itself and how the server is hoisting itself (/ keeping itself alive).

**Comment by vprajapati-tt** [comment]
Specific Runs:

- <https://github.com/tenstorrent/tt-mlir/actions/runs/12167197871/job/33935198039>
- <https://github.com/tenstorrent/tt-mlir/actions/runs/12167197871/job/33943714464>

**Comment by odjuricicTT** [comment]
> When running locally, I noticed that it would open a webpage and restart the server for every testcase. This may potentially be the cause (it's also just inefficient)

You are right, we use model_explorer.visualize, which does try to open the browser. We should switch to visualize_with_config here as well. On the other hand we need to restart the server for every test in order to make sure that if one test fails in a way that crashes the server the others are not affected. I think that it is efficient enough for now, if it starts taking too long we can discuss other solutions.
