### ISSUE TITLE
Hook into perf trace framework for host profiling

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#329]
Use some of the macros and infrastructure provided by the tracy framework that tt-metal uses.  We should be able to piggyback off of their usage, when `ENABLE_TRACY` is enabled.

This should wrap some of the metal runtime routines, especially:
```c++
CQExecutor::execute(::tt::target::metal::EnqueueProgramCommand const *command) {
  ZoneScopedN(command->program()->name()->c_str());
}
```

We can use `FrameMark` to mark the boundary of command queues.

**Comment by kmabeeTT** [comment]
Starting to take a look at this one.

**Comment by kmabeeTT** [comment]
Hey @nsmithtt can you take a look at this cmake linking/dependency problem when you get a chance please? 

I pushed some changes to `kmabee/issue_329_perf_trace` to add some perf tracing (ZoneScoped/FrameMark), and can see it in tracy for some TTMetal silicon tests (screenshot attached, the purple top-most zones are ours). It's basically 3 things:

1. Add Zonescoped/FrameMark tracing to some functions
2. Add TRACY_ENABLE define to `TTRuntimeTTNN`, `TTRuntimeTTMetal` compile
3. Try and link` ${PROJECT_SOURCE_DIR}/third_party/tt-metal/src/tt-metal-build/lib/libtracy.so` to solve missing symbols errors.

![Screenshot 2024-09-14 at 8 33 35 PM](https://github.com/user-attachments/assets/33ab122e-02dd-4126-9df0-6b2eb13c57db)

The define/linking part just looks like this right now:

```
# Optionally compile profiling code and link tracy client for perf profiling.
if (TT_RUNTIME_ENABLE_PERF_TRACE)
  target_link_libraries(TTRuntime PRIVATE ${PROJECT_SOURCE_DIR}/third_party/tt-metal/src/tt-metal-build/lib/libtracy.so)
  target_compile_definitions(TTRuntimeTTNN PUBLIC TRACY_ENABLE)
  target_compile_definitions(TTRuntimeTTMetal PUBLIC TRACY_ENABLE)
endif()
```

**Problem**

I am struggling with finding the right code/fix for number 3 above though. It fails on [CI](https://github.com/tenstorrent/tt-mlir/actions/runs/10866852938/job/30154946482) or fresh repo build because libtracy.so cannot be found right at the start of `cmake --build build` (because of course, tt-metal hasn't been built yet).  

```
cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang-17 -DCMAKE_CXX_COMPILER=clang++-17 -DTTMLIR_ENABLE_RUNTIME=ON -DTTMLIR_ENABLE_RUNTIME_TESTS=ON -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DTT_RUNTIME_ENABLE_PERF_TRACE=ON
cmake --build build
```

But it worked for me locally during development because I had already had tt-metal built successfully (before my changes) with `-DTT_RUNTIME_ENABLE_PERF_TRACE=ON` (which enables metal tracy build, to generate libtracy.so).

On tt-metal side (`third_party/tt-metal/src/tt-metal/tt_metal/CMakeLists.txt`) they link against tracy this way, I am thinking I need to find a way to do the same (?):

```
target_link_libraries(tt_metal PUBLIC compiler_flags $<$<BOOL:${ENABLE_TRACY}>:TracyClient>)
```

I tried pursuing a couple ideas (linking against `TracyClient` instead (got errors because tracy.cmake uses `${PROJECT_SOURCE_DIR}` which now is incorrect) or adding dependency on `tt-metal` to try and make it build first (didn't do anything), but may have done something wrong. From `runtime/lib/CMakeLists.txt`:

```
if (TT_RUNTIME_ENABLE_PERF_TRACE)
  include(${PROJECT_SOURCE_DIR}/third_party/tt-metal/src/tt-metal/cmake/tracy.cmake)
  add_dependencies(TTRuntime tt-metal)  # Hack? Ensure tt-metal is built first. No help.
  target_link_libraries(TTRuntime PRIVATE TracyClient)
  # target_link_libraries(TTRuntime PRIVATE ${PROJECT_SOURCE_DIR}/third_party/tt-metal/src/tt-metal-build/lib/libtracy.so)
  target_compile_definitions(TTRuntimeTTNN PUBLIC TRACY_ENABLE)
  target_compile_definitions(TTRuntimeTTMetal PUBLIC TRACY_ENABLE)
endif()
```

Can you please take a look and see if there is some easy fix?

**Comment by nsmithtt** [comment]
See a909ea67bf23d2e0a9c8702f27f070da7e2f14c7:
- Export `TRACY_LIBRARY` from `third_party/CMakeLists.txt`
- `target_link_libraries(TTRuntimeTTMetal PUBLIC TRACY_LIBRARY)`

**Comment by kmabeeTT** [comment]
Thanks @nsmithtt for the cleanup changes! It almost worked but I needed to add `TRACY_LIBRARY_PATH` to tt-metal `BUILD_BYPRODUCTS` in the same file to solve the error which was a dependency issue (so that cmake knows libtracy.so is generated from tt-metal build).  Going to sqaush changes and for now keep the change just in `runtime/lib/ttmetal/CMakeLists.txt` instead of `runtime/lib/CMakeLists.txt` for both metal/ttnn since it aligns better with other dependencies/linking added to `TTRuntimeTTMetal`.

**Comment by nsmithtt** [comment]
> Thanks @nsmithtt for the cleanup changes! It almost worked but I needed to add `TRACY_LIBRARY_PATH` to tt-metal `BUILD_BYPRODUCTS` in the same file to solve the error which was a dependency issue (so that cmake knows libtracy.so is generated from tt-metal build).  Going to sqaush changes and for now keep the change just in `runtime/lib/ttmetal/CMakeLists.txt` instead of `runtime/lib/CMakeLists.txt` for both metal/ttnn since it aligns better with other dependencies/linking added to `TTRuntimeTTMetal`.

Oh right, makes sense, good catch! Just double check that it works for perf disabled builds because in that case the Tracy lib will not exist.
