### ISSUE TITLE
TTNN runtime doesn't pass grid size to ttnn ops

### ISSUE THREAD

**Issue by odjuricicTT** [tenstorrent/tt-mlir#450]
TTNN runtime passes empty op configurations into TTNN op calls instead of passing attributes that we set in MLIR passes (e.g. grid size), [Example](https://github.com/tenstorrent/tt-mlir/blob/main/runtime/lib/ttnn/program.cpp#L475C1-L477C1):
```
  tensorPool.push_back(::ttnn::operations::matmul::matmul(
      lhs, rhs, std::nullopt, ::ttnn::operations::matmul::Matmul{}));
```

**Comment by odjuricicTT** [comment]
@AleksKnezevic Any suggestions?

**Comment by nsmithtt** [comment]
This is kind of compiler/runtime interface, though I'm guessing the bulk of the code will end up on the runtime side.

**Comment by odjuricicTT** [comment]
@jnie-TT Should we be passing `output_mem_config`, from out output tensor, into op calls [here](https://github.com/tenstorrent/tt-mlir/blob/main/runtime/lib/ttnn/program.cpp#L475C1-L477C1)?
```
  tensorPool.push_back(::ttnn::operations::matmul::matmul(
      lhs, rhs, std::nullopt, ::ttnn::operations::matmul::Matmul{}));
```

In order to get the desired layout on the result of the op. Or is this somehow inferred by TTNN?

**Comment by jnie-TT** [comment]
> @jnie-TT Should we be passing `output_mem_config`, from our output tensor, into op calls [here](https://github.com/tenstorrent/tt-mlir/blob/main/runtime/lib/ttnn/program.cpp#L475C1-L477C1)?
> 
> ```
>   tensorPool.push_back(::ttnn::operations::matmul::matmul(
>       lhs, rhs, std::nullopt, ::ttnn::operations::matmul::Matmul{}));
> ```
> 
> In order to get the desired layout on the result of the op. Or is this somehow inferred by TTNN?

@odjuricicTT yes we should be passing the output memory configs in so that the output tensors are automatically converted to the desired memory config. 

We should also be configuring the input memory config, specifically the shard spec, that captures the shard shape/config the compiler generates for interleaved data as well. One caveat here is that this may or may not affect the op. I talked to the TTNN folks, and it seems that the grid-size may or may not be configurable by the user. For example, unary ops always default to the entire grid if the data is interleaved, and just run empty programs on extra cores, but actually inspect the ShardSpec grid size/shard shape for sharded data. There's no universal way of configuring grid size - it's more of an op-by-op basis.

**Comment by odjuricicTT** [comment]
@jnie-TT Thanks for the clarification!
