### ISSUE TITLE
Create clean_build.sh for ease of development

### ISSUE THREAD

**Issue by vprajapati-tt** [tenstorrent/tt-mlir#523]
Sometimes the build just doesn't go as planned. There a few sources for build errors to occur, so it would be nice to be able to run a script that clears all of the build artifacts and allows for a `clean_build`.

The directories to remove as far as I know:
- `build/`
- `third_party/tt_metal/`

**Comment by nsmithtt** [comment]
It's a great idea for a local script!  I appreciate the idea, but I'm not a fan of checking in scripts that imply a particular workflow, esp since cruft tends to creep into these scripts and are oftentimes not portable between different developer environments.  We use cmake, it implies cmake build system, so `cmake --build build --target clean` can be used.  If you really want to get back to a "fresh clone" state you can use `git clean -fdx`.
