### ISSUE TITLE
Update conv/maxpool `SI32Attr` to use `"int64_t"`

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-mlir#662]
The conv/maxpool op should use `"int64_t"` instead of `SI32Attr` for declaring its op attributes.

**Comment by LPanosTT** [comment]
@nsmithtt I'm not sure how I'm supposed to use `"int64_t"` as an attribute type, its not compiling if I replace it. If you mean to use `I64` instead I can do that. However, I noticed that `I64` is an operand and `I64Attr` is an attribute. It seems to me like we should keep these inputs (kernel_size, stride, etc) as op attributes rather than graph operands. 

What do you think?

**Comment by nsmithtt** [comment]
Yeah you're right, sorry about that.  It seems like the `"int64_t"` syntax is only legal for attributes and types, but not ops.

You can make a custom builder, but not sure it's worth the effort see:
https://github.com/llvm/llvm-project/blob/33325524f5e80a898a7ae875e208a54af132001b/mlir/include/mlir/Dialect/Linalg/TransformOps/LinalgTransformOps.td#L165

**Comment by nsmithtt** [comment]
We can close, unless you feel compelled to make a custom builder

**Comment by LPanosTT** [comment]
> We can close, unless you feel compelled to make a custom builder

We should probably close, I don't really see a reason to not go with the attribute types that are already provided since their simple integers

**Comment by nsmithtt** [comment]
So the custom builder would just give you a convenience constructor to let use just use integers directly.  But yeah, unclear if it's worth it.  Let's close! :)
