### ISSUE TITLE
[TTNN] Produce empty/full tensors in TILE layout.

### ISSUE THREAD

**Issue by uazizTT** [tenstorrent/tt-mlir#850]
For the Eltwise binary ops, the inputs are expected to be in TILE layout. 

The inputs produced for empty/full tensors are not in TILE layout, producing the following error: 

```
Always | FATAL    | Inputs to eltwise binary must be tilized

E     RuntimeError: TT_FATAL @ /home/uaziz/tt-xla/third_party/tt-mlir/src/tt-mlir/third_party/tt-metal/src/tt-metal/ttnn/cpp/ttnn/operations/eltwise/binary/device/binary_device_operation.cpp:63: (input_tensor_a.get_layout() == Layout::TILE && input_tensor_b.get_layout() == Layout::TILE)
E     info:
E     Inputs to eltwise binary must be tilized
```

**Comment by mrakitaTT** [comment]
### Adding discussion from slack for more clarity about the issue:

There is a [bug](https://github.com/tenstorrent/tt-metal/issues/8635) in Metal which causes `ttnn::empty` and `ttnn::full` to assert in `TILE` layout for shapes which are not divisible by tile size, even though padding should be applied. That is why we currently in runtime always invoke these ops only with `ROW_MAJOR` layout, and produced tensors are therefore in `ROW_MAJOR` layout. This didn't cause issues in tt-mlir tests so far because `FullOp` was not even supported in TTIR until we've added it for StableHLO, and `TTIR.EmptyOp` was used exclusively to create output tensor for DPS ops, in which case it doesn't matter what layout it has because that tensor will be replaced anyways with the tensor that said DPS operation produces.

With the introduction of `TTIR.ConstantOp`, which we needed for softmax/mnist graphs, we've now introduced additional use cases of `EmptyOp` and `FullOp`, which is to create tensors which will be used as inputs to other ops. That is why layout of these tensors suddenly matters, because ttnn eltwise binary ops don't allow inputs with mismatched layout. So for example if some binary op expects its inputs to be in `TILE` layout, we need to produce empty/full tensors in `TILE` layout.

To get around this issue I am currently converting produced tensors in runtime to `TILE` layout. Unfortunately, tilizing in ttnn currently works only for bfp16 and doesn't work for f32, so in that case I am doing even more massive hack which is just doing this: `tensor.set_layout(::ttnn::Layout::TILE);`

Of course, this it problematic for several reasons:
- We don't want to have hardcoded output layout, we want to inferr it from the graph. This is currently blocked by issue [#272](https://github.com/tenstorrent/tt-mlir/issues/272). For `full` op it might even be okay, because produced tensor by that op is currently only used as input to other ops, so it is probably safe to always assume `TILE` layout. For `empty` op it itsn't the case though.
- It isn't safe to just change the layout attribute on tensor, its underlying storage, shape, padding and other internals have to be properly changed too. I thought that maybe this will work for single element tensor, but it seems that we get weird results and that is probably why MNIST test is failing with PCC error right now.

I think we should prioritize issues [#272](https://github.com/tenstorrent/tt-mlir/issues/272) and [metal#8635](https://github.com/tenstorrent/tt-metal/issues/8635). The metal issue seems like a really easy thing to fix, it seems that they are just not taking properly padding into consideration with the assertion they have. That issue is opened since May and it probably just fell through the cracks for them. Maybe some of us could help with fixing it. Any other solutions on our side would probably be massive hacks and involve changing layouts all across the graph.

I'll ping Mladen to help us with escalating this issue to Metal.

**Comment by mrakitaTT** [comment]
Fixed as part of https://github.com/tenstorrent/tt-mlir/issues/582
